Homework2
KseniaKotova/TMS_projects pull request #1
Opened 2022-02-19 17:35 UTC by KseniaKotova

Task: https://www.figma.com/file/16bdlWFoZXXIpyyZmwy9JU/Logoipsum?node-id=0%3A1
Created: 
![task](https://user-images.githubusercontent.com/91899117/154812205-514edde6-3060-4087-8075-814f64a3610a.jpg)

2022-02-19 18:56 UTC, shuliakleonid requested changes

2022-02-19 18:56 UTC, shuliakleonid commented on lesson 2/style.css
> +    margin: 0;
if you do not need comments, delete it

2022-02-19 18:56 UTC, shuliakleonid commented on lesson 2/style.css
> +    padding-top: 14px;
empty row

2022-02-19 18:56 UTC, shuliakleonid commented on lesson 2/style.css
> +.btn_inner{
after class do please empty line

2022-02-19 18:56 UTC, shuliakleonid commented on lesson 2/style.css
> +
empty row

2022-02-19 19:00 UTC, shuliakleonid requested changes

2022-02-19 19:00 UTC, shuliakleonid commented on lesson 2/index.html
> +            </div>
add alt

2022-02-19 19:00 UTC, shuliakleonid commented on lesson 2/style.css
> +   margin-right: 100px;
can you write with main margin

2022-02-19 19:00 UTC, shuliakleonid commented
# Good work

2022-02-20 11:31 UTC, shuliakleonid approved these changes

2022-02-20 11:31 UTC, shuliakleonid commented on lesson 2/index.html
> +                    <a class = "nav__link" href = "#">Home</a>
<nav class = "header__nav">
your may write like <nav class = "nav"> it's correct or if you need two class 
<nav class = "header__nav nav">
but it's not mistake

2022-02-20 11:31 UTC, shuliakleonid commented on lesson 2/index.html
> +                    <button class = "btn__inner">Get Started</button>
the same with button

2022-02-20 11:31 UTC, shuliakleonid commented on lesson 2/index.html
> +        <div class="logo__about">
may be logo

2022-02-21 08:55 UTC, AlexisKozlov approved these changes
Thanks, great work!

2022-02-22 10:31 UTC, egkirpichev approved these changes
👍

2022-02-22 16:01 UTC, merged